// Generated by CoffeeScript 1.6.3
(function() {
  app.controller('testCtrl', [
    '$rootScope', 'TestModal', function($scope, TestModal) {
      $scope.example1 = function() {
        return TestModal.openAlert('Some alert message');
      };
      $scope.example2 = function() {
        return TestModal.openConfirm('Do you want to hire me?').then(function() {
          return alert('Goood news )');
        }, function() {
          return alert('Bad news *(');
        });
      };
      return $scope.example3 = function() {
        return TestModal.open({
          title: 'Send a comment',
          templateUrl: 'templates/sendmail.html',
          buttons: [
            {
              label: 'Send',
              callback: function() {
                return this.close();
              }
            }
          ]
        });
      };
    }
  ]);

}).call(this);
